// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-stores.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/list-stores.ts
var list_stores_default = defineTool({
  name: "list_stores",
  title: "Lister les magasins",
  description: "List the stores the signed-in user can access, with their planning options.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_my_stores");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { stores: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_employees_default = defineTool2({
  name: "list_employees",
  title: "Lister les collaborateurs",
  description: "List employees of a store (name, role, contract hours, active status).",
  inputSchema: {
    store_id: z.string().uuid().optional().describe("Store id; omit to list all accessible employees."),
    include_inactive: z.boolean().optional().describe("Include inactive employees (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, include_inactive }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("employees").select("id, name, last_name, role, contract_hours, is_active, is_cadre, sort_order, store_id").order("sort_order", { ascending: true });
    if (store_id) query = query.eq("store_id", store_id);
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { employees: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-week-schedule.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_week_schedule_default = defineTool3({
  name: "get_week_schedule",
  title: "Planning d'une semaine",
  description: "Get the weekly schedule (start/end and lunch breaks per day) for a store and a week starting on Monday (YYYY-MM-DD).",
  inputSchema: {
    store_id: z2.string().uuid().describe("Store id."),
    week_start: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Monday of the week, local date YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, week_start }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: employees, error: empError } = await supabase.from("employees").select("id, name, last_name, role, contract_hours, sort_order").eq("store_id", store_id).eq("is_active", true).order("sort_order", { ascending: true });
    if (empError) return { content: [{ type: "text", text: empError.message }], isError: true };
    const ids = (employees ?? []).map((e) => e.id);
    if (ids.length === 0) {
      return { content: [{ type: "text", text: "[]" }], structuredContent: { rows: [] } };
    }
    const { data: schedules, error } = await supabase.from("weekly_schedules").select("*").eq("week_start", week_start).in("employee_id", ids);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byEmployee = new Map((schedules ?? []).map((s) => [s.employee_id, s]));
    const rows = (employees ?? []).map((e) => ({ employee: e, schedule: byEmployee.get(e.id) ?? null }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { week_start, rows }
    };
  }
});

// src/lib/mcp/tools/list-leaves.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_leaves_default = defineTool4({
  name: "list_leaves",
  title: "Lister les cong\xE9s",
  description: "List leaves/absences overlapping a date range, optionally filtered by store.",
  inputSchema: {
    date_start: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Range start, YYYY-MM-DD."),
    date_end: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Range end, YYYY-MM-DD."),
    store_id: z3.string().uuid().optional().describe("Limit to employees of this store.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_start, date_end, store_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("conges").select("id, employee_id, type, date_start, date_end, notes, employees(name, last_name, role, store_id)").lte("date_start", date_end).gte("date_end", date_start).order("date_start", { ascending: true });
    if (store_id) query = query.eq("employees.store_id", store_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = store_id ? (data ?? []).filter((r) => r.employees) : data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { leaves: rows }
    };
  }
});

// src/lib/mcp/tools/create-leave.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_leave_default = defineTool5({
  name: "create_leave",
  title: "Cr\xE9er un cong\xE9",
  description: "Create a leave/absence for an employee over a date range.",
  inputSchema: {
    employee_id: z4.string().uuid().describe("Employee id."),
    type: z4.string().trim().min(1).describe("Leave type code (e.g. CA, RC, MAL)."),
    date_start: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("First day, YYYY-MM-DD."),
    date_end: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Last day, YYYY-MM-DD."),
    notes: z4.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ employee_id, type, date_start, date_end, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (date_end < date_start) {
      return { content: [{ type: "text", text: "date_end must be on or after date_start" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conges").insert({ employee_id, type, date_start, date_end, notes: notes ?? null }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { leave: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var whoami_default = defineTool6({
  name: "whoami",
  title: "Mon compte",
  description: "Return the signed-in user's email and application role (admin, manager, editor, user).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_my_role");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = { user_id: ctx.getUserId(), email: ctx.getUserEmail(), role: data ?? "user" };
    return {
      content: [{ type: "text", text: JSON.stringify(profile) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pkxrmkijomabvzmszcxr";
var mcp_default = defineMcp({
  name: "planning-fnac",
  title: "Planning Fnac",
  version: "1.0.0",
  instructions: "Tools for Planning Fnac (Fnac Belgium store scheduling). Use `whoami` and `list_stores` first to know the user's role and accessible stores, then `list_employees`, `get_week_schedule` (week_start = Monday, local YYYY-MM-DD) and `list_leaves`. `create_leave` adds an absence. All data is scoped by store and by the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_stores_default, list_employees_default, get_week_schedule_default, list_leaves_default, create_leave_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
